apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: >-
      {"input":{"containers":[{"name":"station-catalog-1"}]},"output":{"containers":[{"limits":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"station-catalog-1"}]},"modified":true}
  labels:
    app: station-catalog-deployment
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: { }
            'f:app': { }
        'f:spec':
          'f:progressDeadlineSeconds': { }
          'f:replicas': { }
          'f:revisionHistoryLimit': { }
          'f:selector': { }
          'f:strategy':
            'f:rollingUpdate':
              .: { }
              'f:maxSurge': { }
              'f:maxUnavailable': { }
            'f:type': { }
          'f:template':
            'f:metadata':
              'f:labels':
                .: { }
                'f:app': { }
            'f:spec':
              'f:containers':
                'k:{"name":"station-catalog-1"}':
                  .: { }
                  'f:env':
                    .: { }
                    'k:{"name":"SPRING_DATASOURCE_PASSWORD"}':
                      .: { }
                      'f:name': { }
                      'f:valueFrom':
                        .: { }
                        'f:configMapKeyRef':
                          .: { }
                          'f:key': { }
                          'f:name': { }
                    'k:{"name":"SPRING_DATASOURCE_URL"}':
                      .: { }
                      'f:name': { }
                      'f:valueFrom':
                        .: { }
                        'f:configMapKeyRef':
                          .: { }
                          'f:key': { }
                          'f:name': { }
                    'k:{"name":"SPRING_DATASOURCE_USERNAME"}':
                      .: { }
                      'f:name': { }
                      'f:valueFrom':
                        .: { }
                        'f:configMapKeyRef':
                          .: { }
                          'f:key': { }
                          'f:name': { }
                  'f:image': { }
                  'f:imagePullPolicy': { }
                  'f:name': { }
                  'f:resources': { }
                  'f:terminationMessagePath': { }
                  'f:terminationMessagePolicy': { }
              'f:dnsPolicy': { }
              'f:restartPolicy': { }
              'f:schedulerName': { }
              'f:securityContext': { }
              'f:terminationGracePeriodSeconds': { }
      manager: GoogleCloudConsole
      operation: Update
      time: '2021-12-27T18:57:22Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': { }
        'f:status':
          'f:availableReplicas': { }
          'f:conditions':
            .: { }
            'k:{"type":"Available"}':
              .: { }
              'f:lastTransitionTime': { }
              'f:lastUpdateTime': { }
              'f:message': { }
              'f:reason': { }
              'f:status': { }
              'f:type': { }
            'k:{"type":"Progressing"}':
              .: { }
              'f:lastTransitionTime': { }
              'f:lastUpdateTime': { }
              'f:message': { }
              'f:reason': { }
              'f:status': { }
              'f:type': { }
          'f:observedGeneration': { }
          'f:readyReplicas': { }
          'f:replicas': { }
          'f:updatedReplicas': { }
      manager: kube-controller-manager
      operation: Update
      time: '2021-12-27T19:00:28Z'
  name: station-catalog-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: station-catalog-deployment
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: station-catalog-deployment
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: station-catalog-deployment-config-mf7u
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_USERNAME
                  name: station-catalog-deployment-config-mf7u
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_PASSWORD
                  name: station-catalog-deployment-config-mf7u
          image: >-
            gcr.io/custom-seeker-334114/github.com/rso-epolnilnica/station-catalog
          imagePullPolicy: IfNotPresent
          name: station-catalog-1
          resources:
            limits:
              cpu: 200m
              ephemeral-storage: 1Gi
              memory: 1Gi
            requests:
              cpu: 200m
              ephemeral-storage: 1Gi
              memory: 1Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
      securityContext:
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: station-catalog-deployment
  managedFields:
    - apiVersion: autoscaling/v2beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: { }
            'f:app': { }
        'f:spec':
          'f:maxReplicas': { }
          'f:metrics': { }
          'f:minReplicas': { }
          'f:scaleTargetRef':
            'f:apiVersion': { }
            'f:kind': { }
            'f:name': { }
      manager: GoogleCloudConsole
      operation: Update
      time: '2021-12-27T17:18:23Z'
    - apiVersion: autoscaling/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: { }
            'f:autoscaling.alpha.kubernetes.io/conditions': { }
            'f:autoscaling.alpha.kubernetes.io/current-metrics': { }
        'f:status':
          'f:currentCPUUtilizationPercentage': { }
          'f:currentReplicas': { }
          'f:desiredReplicas': { }
          'f:lastScaleTime': { }
      manager: vpa-recommender
      operation: Update
      time: '2021-12-27T17:23:27Z'
  name: station-catalog-deployment-hpa-tqlx
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: station-catalog-deployment
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  generateName: station-catalog-deployment-
  labels:
    app: station-catalog-deployment
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': { }
          'f:labels':
            .: { }
            'f:app': { }
        'f:spec':
          'f:externalTrafficPolicy': { }
          'f:ports':
            .: { }
            'k:{"port":80,"protocol":"TCP"}':
              .: { }
              'f:port': { }
              'f:protocol': { }
              'f:targetPort': { }
          'f:selector':
            .: { }
            'f:app': { }
          'f:sessionAffinity': { }
          'f:type': { }
      manager: GoogleCloudConsole
      operation: Update
      time: '2021-12-27T19:28:30Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: { }
            'v:"service.kubernetes.io/load-balancer-cleanup"': { }
        'f:status':
          'f:loadBalancer':
            'f:ingress': { }
      manager: kube-controller-manager
      operation: Update
      time: '2021-12-27T19:29:15Z'
  name: station-catalog-deployment-wnlqg
  namespace: default
spec:
  clusterIP: 10.93.130.34
  clusterIPs:
    - 10.93.130.34
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 31971
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: station-catalog-deployment
  sessionAffinity: None
  type: LoadBalancer
